routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Auth::routes();

Route::group(['middleware' => ['auth']], function() {
    Route::group(['prefix' => 'admin', 'namespace' => 'Admin'], function () {
        Route::get('/', 'DashboardController@index')->name('dashboard');
        Route::resource('category', 'CategoryController');
        Route::resource('customer', 'CustomerController');
        Route::resource('settings', 'SettingController');

    });

    Route::resource('file', 'FileController');

    Route::get('/logout', '\App\Http\Controllers\Auth\LoginController@logout');
});

Route::get('/', 'HomeController@index')->name('home');
Route::get('/order', 'Admin\CustomerController@store')->name('order');
Route::get('/orderSuccess', 'HomeController@orderSuccess')->name('orderSuccess');
Route::get('/about', 'HomeController@about')->name('about');

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Input;
use App\Entities\Customer;
use App\Entities\Setting;

/**
 * Class HomeController
 * @package App\Http\Controllers
 */
class HomeController extends Controller
{
    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        $amount_product = Setting::where('key','amount_product')->orderBy('created_at', 'desc')->first();
        if(!$amount_product){
            $amount_product = 3243;
        }else{
            $amount_product = $amount_product->value;
        }
        return view('home.index')->with('amount_product',$amount_product);
    }
    public function orderSuccess()
    {
        $code = Input::get('code');
        if(!$code || $code ==''){
            return redirect('/');
        }
        if($code != 'SUCCESS'){
            $customer = Customer::where('code',$code)->first();
            if(!$customer){
                return redirect('/');
            }
            if($customer->color == 'silver'){
                $link_img = './images/40-alu-silver-sport-white-nc-s4-1up.png';
            }
            if($customer->color == 'gold'){
                $link_img = './images/44-alu-gold-sport-pink-sand-s4-gallery1.jpeg';
            }
            if($customer->color == 'black'){
                $link_img = './images/44-alu-space-sport-black-s4-gallery1.jpeg';
            }
        }
        else{
            $customer = Customer::first();
            $link_img = './images/40-alu-silver-sport-white-nc-s4-1up.png';
        }

        return view('home.orderSuccess')->with(['code'=>$code,'customer'=>$customer,'link_img'=>$link_img]);
    }

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function about()
    {
        return view('home.about');
    }

    public function loan()
    {
        return view('home.loan');
    }
}

resources/views/admin/home/index.blade.php
@extends('admin.layouts.app')

@section('title', 'Main page')

@section('content')
    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-lg-6">
                <div class="ibox ">
                    <div class="ibox-title">
                        <h5>Summary
                        </h5>
                    </div>
                    <div class="ibox-content">
                        <div>
                            <p>Tổng cộng: <span class="money" style="font-weight: bold;color: #c71212;">{{$total}}</span></p>
                            <span style="margin-bottom: 10px">(Thành công: <span class="money" style="font-weight: bold;color: #c71212;">{{$success}}</span> , Đang đợi: <span class="money" style="font-weight: bold;color: #c71212;">{{$waiting}}</span>)</span>
                            <p>Chi phí: <span class="money" style="font-weight: bold;color: #c71212;">{{$cost}}</span></p>
                            <p>Lợi nhuận: <span id="profit" class="money" style="font-weight: bold;color: #c71212;">{{$success-$cost}}}</span> </p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-6">
                <div class="ibox ">
                    <div class="ibox-title">
                        <h5>Cài đặt
                        </h5>
                    </div>
                    <div class="ibox-content">
                        <div>
                            <form action="{{route('settings.store')}}" method="post">
                                {{ csrf_field() }}
                                <div class="form-group row">
                                    <select class="form-control m-b" name="key">
                                        <option selected value="facebook_ads">Thêm chi phí Quảng cáo Facebook</option>
                                        <option value="amount_product">Số lượng sản phẩm</option>
                                    </select>
                                    <input class="form-control" name="value">
                                </div>

                                <button class="btn btn-sm btn-primary" type="submit">Xong</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('scripts')
@endsection

resources/views/admin/home/minor.blade.php
@extends('admin.layouts.app')

@section('title', 'Minor page')

@section('content')
  <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-lg-12">
                <div class="text-center m-t-lg">
                    <h1>
                        Simple example of second view
                    </h1>
                    <small>Writen in minor.blade.php file.</small>
                </div>
            </div>
        </div>
    </div>
@endsection