routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Auth::routes();

Route::group(['middleware' => ['auth']], function() {
    Route::group(['prefix' => 'admin', 'namespace' => 'Admin'], function () {
        Route::get('/', 'DashboardController@index')->name('dashboard');
        Route::resource('category', 'CategoryController');
        Route::resource('customer', 'CustomerController');
        Route::resource('settings', 'SettingController');

    });

    Route::resource('file', 'FileController');

    Route::get('/logout', '\App\Http\Controllers\Auth\LoginController@logout');
});

Route::get('/', 'HomeController@index')->name('home');
Route::get('/order', 'Admin\CustomerController@store')->name('order');
Route::get('/orderSuccess', 'HomeController@orderSuccess')->name('orderSuccess');
Route::get('/about', 'HomeController@about')->name('about');

resources/views/admin/layouts/app.blade.php
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>@yield('title')</title>


    <link rel="stylesheet" href="{{ asset('css/vendor.css') }}" />
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link href="{{ asset('css/admin.css') }}" rel="stylesheet">
    <link href="{{ asset('css/plugins/iCheck/custom.css') }}" rel="stylesheet">
    <link href="{{ asset('css/plugins/switchery/switchery.css') }}" rel="stylesheet">
    <link href="{{ asset('css/plugins/dropzone/dropzone.css') }}" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{{ asset('DataTables/datatables.min.css') }}"/>

</head>
<body>

  <!-- Wrapper-->
    <div id="wrapper">

        <!-- Navigation -->
        @include('admin.layouts.navigation')

        <!-- Page wraper -->
        <div id="page-wrapper" class="gray-bg">

            <!-- Page wrapper -->
            @include('admin.layouts.topnavbar')

            <!-- Main view  -->
            @yield('content')

            <!-- Footer -->
            @include('admin.layouts.footer')

        </div>
        <!-- End page wrapper-->

    </div>
    <!-- End wrapper-->

<script src="{{ asset('js/app.js') }}" type="text/javascript"></script>
<script src="{{ asset('js/plugins/sweetalert/sweetalert.min.js') }}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js"></script>
<script src="{{ asset('js/common.js') }}"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.15/jquery.mask.min.js"></script>
  <script type="text/javascript">
      $(document).ready(function () {
          $('.money').mask('000.000.000.000.000 vnđ', {reverse: true});
      })
  </script>
@section('scripts')
@show

</body>
</html>

resources/views/admin/layouts/navigation.blade.php
<nav class="navbar-default navbar-static-side" role="navigation">
    <div class="sidebar-collapse">
        <ul class="nav metismenu" id="side-menu">
            <li class="nav-header">
                <div class="dropdown profile-element">
                    <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                        <span class="clear">
                            <span class="block m-t-xs">
                                <strong class="font-bold">{{ Auth::user()->name }}</strong>
                                <span class="text-muted text-xs"><b class="caret"></b></span>
                            </span>
                        </span>
                    </a>
                    <ul class="dropdown-menu animated fadeInRight m-t-xs">
                        <li><a href="{{ route('home') }}">{!! __('title.home') !!}</a></li>
                        <li><a href="{{ route('logout') }}">{!! __('title.logout') !!}</a></li>
                    </ul>
                </div>
                <div class="logo-element">
                    CT
                </div>
            </li>
            <li class="{!! Request::is('admin') ? 'active' : '' !!}">
                <a href="{{ route('dashboard') }}">
                    <i class="fa fa-th-large"></i>
                    <span class="nav-label">{!! __('dashboard.dashboard') !!}</span>
                </a>
            </li>
            <li class="treeview {!! Request::is('admin/customer*') ? 'active' : '' !!}">
                <a href="{{ route('customer.index') }}">
                    <i class="fa fa-th-large"></i>
                    <span class="nav-label">{!! __('customer.manageCustomers') !!}</span>
                    <span class="fa arrow"></span>
                </a>
                <ul class="nav nav-second-level">
                    <li class="{{ isActiveRoute('customer.index') }}"><a href="{{ route('customer.index') }}">{!! __('title.list') !!}</a></li>
                </ul>
            </li>
        </ul>

    </div>
</nav>

resources/views/admin/layouts/topnavbar.blade.php
<div class="row border-bottom">
    <nav class="navbar navbar-static-top white-bg" role="navigation" style="margin-bottom: 0">
        <div class="navbar-header">
            <a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"></i> </a>
        </div>
        @if (isset($pageTitle))
            <h2 class="page-title">{!! $pageTitle !!}</h2>
        @endif
        <ul class="nav navbar-top-links navbar-right">
            <li>
                <a href="{{ url('/logout') }}">
                    <i class="fa fa-sign-out"></i> {!! __('title.logout') !!}
                </a>
            </li>
        </ul>
    </nav>
</div>