routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Auth::routes();

Route::group(['middleware' => ['auth']], function() {
    Route::group(['prefix' => 'admin', 'namespace' => 'Admin'], function () {
        Route::get('/', 'DashboardController@index')->name('dashboard');
        Route::resource('category', 'CategoryController');
        Route::resource('customer', 'CustomerController');
        Route::resource('settings', 'SettingController');

    });

    Route::resource('file', 'FileController');

    Route::get('/logout', '\App\Http\Controllers\Auth\LoginController@logout');
});

Route::get('/', 'HomeController@index')->name('home');
Route::get('/order', 'Admin\CustomerController@store')->name('order');
Route::get('/orderSuccess', 'HomeController@orderSuccess')->name('orderSuccess');
Route::get('/about', 'HomeController@about')->name('about');

app/Customer.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Customer extends Model
{
    //
}

app/Http/Controllers/Admin/CustomerController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Services\CustomerService;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Yajra\DataTables\DataTables;


class CustomerController extends Controller
{
    private $customerService;

    public function __construct(CustomerService $customerService)
    {
        $this->customerService = $customerService;
    }

    /**
     * Display a listing of the resource.
     *
     * @param Request $request
     * @return \Illuminate\Http\Response
     * @throws \Exception
     */
    public function index(Request $request)
    {
        if ($request->ajax()) {
            return DataTables::of($this->customerService->all())
                ->make(true);
        }
        return view('admin.customer.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        var_dump($request->all());
        try {
            $data =$request->all();
            if($data['coupon'])
            $data['price'] = $data['price'] - $data['price'] *$data['coupon'] /100;
            var_dump($data);
            $result = $this->customerService->create($data);

            return redirect()->route('orderSuccess',['code'=>$result->code]);
        } catch (\Illuminate\Database\QueryException $e) {
            $errorCode = $e->errorInfo[1];
            $message = $e->getMessage();
            if ($errorCode == 1062){
                $message = __('customer.duplicateEntryError');
            }
            return redirect()->route('/');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        try {
            $result = $this->customerService->update($request->all(), $id);

            return response()->json([
                'status' => true,
                'message' => __('customer.updateSuccess'),
                'data' => [
                    'id' => $result->id
                ]
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'status' => false,
                'message' => $e->getMessage()
            ]);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try {
            DB::beginTransaction();
            $this->customerService->delete($id);
            DB::commit();
            return response()->json([
                'status' => true,
                'message' => __('customer.deleteSuccess'),
            ]);
        } catch (\Exception $exception) {
            DB::rollBack();
            return response()->json([
                'status' => false,
                'message' => $exception->getMessage()
            ]);
        }
    }
}

resources/views/admin/customer/create.blade.php
@extends('admin.layouts.app')

@section('title', 'Main page')

@section('content')
    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-lg-12">
                <div class="ibox">
                    <div class="ibox-content p-md">
                        <form method="post" class="form-horizontal" id="category-create-form" action="{{ route('category.store') }}">
                            <div class="form-group"><label class="col-sm-2 control-label">{!! __('category.categoryTitle') !!}</label>
                                <div class="col-sm-10">
                                    <input type="text" class="form-control" name="title" required>
                                </div>
                            </div>
                            <div class="hr-line-dashed"></div>
                            <div class="form-group"><label class="col-sm-2 control-label">{!! __('title.image') !!}</label>
                                <div class="col-sm-10 dropzone" id="file-dropzone">
                                    <div class="dropzone-previews"></div>
                                </div>
                                <input type="hidden" name="image">
                            </div>
                            <div class="hr-line-dashed"></div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label">{!! __('category.brands') !!}</label>
                                <div class="col-sm-10">
                                    <table class="table table-sm dynamic-table" id="brands-table">
                                        <tbody style="border-top: none">
                                        <tr class="dt-row-template">
                                            <td>
                                                <input type="text" name="brand_title" class="form-control">
                                            </td>
                                            <td width="10%">
                                                <div class="btn-group btn-group-sm inline" style="height: 38px;">
                                                    <button type="button" class="btn btn-default border dt-insert-row"><i class="fa fa-plus"></i></button>
                                                    <button type="button" class="btn btn-default border dt-remove-row"><i class="fa fa-minus"></i></button>
                                                </div>
                                            </td>
                                        </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                            <div class="hr-line-dashed"></div>
                            <div class="form-group">
                                <div class="col-sm-4 col-sm-offset-2">
                                    <button class="btn btn-white" type="submit">{!! __('title.cancel') !!}</button>
                                    <button class="btn btn-primary" type="submit">{!! __('title.save') !!}</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('scripts')
    <script>
        @php
            $phrases = \App\Common\Helpers\StringHelper::getPhrases([
                'title'
            ]);
        @endphp
        const phrases = @json($phrases);
        const urls = {
        }
    </script>
    <script type="text/javascript" src="{{ asset('js/dynamic-table.js') }}"></script>
    <script type="text/javascript" src="{{ asset('js/admin/category-create.js') }}"></script>
@endsection

resources/views/admin/customer/index.blade.php
@extends('admin.layouts.app')

@section('title', 'Main page')

@section('content')
    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-lg-12">
                <div class="ibox">
                    <div class="ibox-content p-md" style="overflow: scroll">
                        <table id="customer-list-table" class="table table-striped table-hover">
                        <thead>
                        <tr>
                            <th>ID</th>
                            <th>{!! __('customer.customerTitle') !!}</th>
                            <th>SĐT</th>
                            <th>Địa chỉ</th>
                            <th>Giá</th>
                            <th>Phần trăm giảm</th>
                            <th>Mã đơn hàng</th>
                            <th>Status</th>
                            <th>{!! __('title.actions') !!}</th>
                        </tr>
                        </thead>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('scripts')
    <script type="text/javascript" src="{{ asset('DataTables/datatables.min.js') }}"></script>
    <script>
                @php
                    $phrases = \App\Common\Helpers\StringHelper::getPhrases([
                        'title'
                    ]);
                @endphp
        const phrases = @json($phrases);
        const urls =  {
            'customer.index': '{{ route("customer.index") }}',
            'customer.update': '{{ route("customer.update", ":id") }}',
            'customer.destroy': '{{ route("customer.destroy", ":id") }}'
        }
    </script>
    <script type="text/javascript" >
        $(document).ready(function () {
            let $customer_table = $('#customer-list-table').DataTable({
                processing: true,
                serverSide: true,
                // language: getDataTableLanguage(),
                searching: true,
                ajax: {
                    url: urls['customer.index']
                },
                columns: [
                    {
                        data: 'id',
                        name: 'id'
                    },
                    {
                        data: 'name',
                        name: 'name',
                        className: 'text-center',
                    },
                    {
                        data: 'phone',
                        name: 'phone',
                        className: 'text-center',
                    },
                    {
                        data: 'address',
                        name: 'address',
                        className: 'text-center',
                    },
                    {
                        data: 'price',
                        name: 'price',
                        className: 'text-center',
                        render:function (data,type,full,meta) {
                            return `<p class="text-center money" style="font-weight: bold;color: #c71212;">${data}</p>`
                        }
                    },
                    {
                        data: 'coupon',
                        name: 'coupon',
                        className: 'text-center',
                        render:function (data,type,full,meta) {
                            return `${data}%`
                        }
                    },
                    {
                        data: 'code',
                        name: 'code',
                        className: 'text-center',

                    },
                    {
                        data: 'status',
                        name: 'status',
                        className: 'text-center',
                        render:function (data,type,full,meta) {
                            if(data == 0){
                                return `<p class="text-center" style="font-weight: bold;color: #f8ac59;">Chờ xử lý</p>`
                            }else if(data == 1){
                                return `<p class="text-center" style="font-weight: bold;color: #1a7bb9;">Thành công</p>`
                            }else {
                                return `<p class="text-center" style="font-weight: bold;color: #c71212;">Thất bại</p>`
                            }
                        }
                    },
                    {
                        data: null,
                        name: null,
                        sortable: false,
                        className: 'text-center',
                        render: function (data, type, full, meta) {
                            return `<button class="btn btn-sm btn-success success-customer-button" data-id="${full.id}">Thành công</button>
                            <button class="btn btn-sm btn-danger fail-customer-button" data-id="${full.id}">Thất bại</button>
                            <button class="btn btn-sm btn-default delete-customer-button" data-id="${full.id}">${phrases.title.delete}</button>`;
                        }
                    }
                ]
            });



            $('#customer-list-table').on('click', '.success-customer-button', function () {
                let customer_id = $(this).data('id');
                swal({
                    title: phrases.title.confirm,
                    text: 'Bạn có chắc chắn muốn Xác nhận khách hàng này ?',
                    type: 'warning',
                    buttons: true
                }).then(function (value) {
                    if (value) {
                        $.ajax({
                            url: urls['customer.update'].replace(':id', customer_id),
                            data: {
                                status: 1,
                            },
                            method: 'put',
                            success: function (response) {
                                if (response.status) {
                                    swal(phrases.title.success, response.message, "success");
                                    $customer_table.ajax.reload();
                                } else {
                                    swal(phrases.title.error, response.message, "error");
                                }
                            }
                        })
                    }
                })
            });
            $('#customer-list-table').on('click', '.fail-customer-button', function () {
                let customer_id = $(this).data('id');
                swal({
                    title: phrases.title.confirm,
                    text: 'Bạn có chắc chắn muốn Xác nhận khách hàng này ?',
                    type: 'warning',
                    buttons: true
                }).then(function (value) {
                    if (value) {
                        $.ajax({
                            url: urls['customer.update'].replace(':id', customer_id),
                            data: {
                                status: 2,
                            },
                            method: 'put',
                            success: function (response) {
                                if (response.status) {
                                    swal(phrases.title.success, response.message, "success");
                                    $customer_table.ajax.reload();
                                } else {
                                    swal(phrases.title.error, response.message, "error");
                                }
                            }
                        })
                    }
                })
            });
            $('#customer-list-table').on('click', '.delete-customer-button', function () {
                let customer_id = $(this).data('id');
                swal({
                    title: phrases.title.confirm,
                    text: 'Bạn có chắc chắn muốn xóa khách hàng này ?',
                    type: 'warning',
                    buttons: true
                }).then(function (value) {
                    if (value) {
                        $.ajax({
                            url: urls['customer.destroy'].replace(':id', customer_id),
                            method: 'delete',
                            success: function (response) {
                                if (response.status) {
                                    swal(phrases.title.success, response.message, "success");
                                    $customer_table.ajax.reload();
                                } else {
                                    swal(phrases.title.error, response.message, "error");
                                }
                            }
                        })
                    }
                })
            });
        });

    </script>
@endsection